# ~/.config/starship.toml

palette = 'colors'

command_timeout = 3600

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false 

format = """
 󰳟\
$directory\
${custom.giturl}\
$git_branch\
$git_state\
$git_status\
$line_break\
$character
"""

right_format = """$all"""

[palettes.colors]
mustard = '#af8700'
color1 = '#f3b2e3'
color2 = '#4d1f46'
color3 = '#d2c2cb'
color4 = '#241e22'
color5 = '#4d1f46'
color6 = '#181216'
color7 = '#181216'
color8 = '#f3b2e3'
color9 = '#f5b9a5'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = " "
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
# show_always = true
# style_user = "bg:transparent fg:color1"
# style_root = "bg:transparent fg:color1"
# format = '[ $user ]($style)'

[directory]
style = "sapphire"
# style = "fg:color8"
format = "[ $path ]($style)"
#truncation_length = 4
#truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[os]
disabled = true
#style = "bg:surface0 fg:text"

[custom.giturl]
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL=" "
else
    GIT_REMOTE_SYMBOL=" "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
format = "at $output"

[git_branch]
symbol = "[](color2) "
style = "fg:color1 bg:color2"
format =  '  on [$symbol$branch]($style)[](color2)'

[git_status]
format = ' [($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
format = '[ $symbol( $version) ]($style)'

[c]
symbol = " "
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = ""
format = '[ $symbol( $version) ]($style)'
detect_files = ["go.mod"]

[php]
symbol = ""
format = '[ $symbol( $version) ]($style)'

[java]
symbol = " "
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
format = '[ $symbol( $version) ]($style)'

[docker_context]
symbol = ""
format = '[ $symbol( $context) ]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:mantle bg:foam)]($style)'

[line_break]
disabled = true 

[character]
disabled = false
success_symbol = "[❯](color8 bold)"
error_symbol = "[❯](@{error})"
vicmd_symbol = "[❮](#f9e2af)"
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'


